### ISSUE TITLE
LG device, NullPointerException

### ISSUE THREAD

**Issue by p-gentili** [OneButtonDeveloper/AndroidInfraRed#1]
Hi, I've received a crash report with this message:

    java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.pm.PackageManager 
    android.content.Context.getPackageManager()' on a null object reference at 
    com.lge.hardware.IRBlaster.IRBlaster$8.run(IRBlaster.java:1938)

LG-D855, API 21

**Comment by bril-andrew** [comment]
In my main app all working fine, so or problem in LG QRemoteSDK.jar, or how the library is used.
Please, make sure that Context parameter is not null when your creating transmitters. Or try to figure out why Context in LgTransmitter is null.

**Comment by p-gentili** [comment]
Should I use the updated code or the .aar in the latest release?

**Comment by OneButtonDeveloper** [comment]
I added the latest release now, so you can try it.
